[build]
  base = "terramedic"
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

[forms.newsletter-signup.actions]
  [forms.newsletter-signup.actions.email]
    to = "info@terramedic.org"
    subject = "New Newsletter Signup"

[forms.contact-form.actions]
  [forms.contact-form.actions.email]
    to = "info@terramedic.org"
    subject = "New Contact Form Submission"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
